version: '3'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3000:80'
    depends_on:
      - api
      - mobile-client

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api:/app

  mobile-client:
    stdin_open: true

    build:
      context: ./mobile-client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./mobile-client:/app
